//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     — Updated to include modal Login / Register controls.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevArt {

    public partial class SiteMaster {

        /// <summary>form1 control.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>TitleContent control.</summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder TitleContent;

        /// <summary>HeadContent control.</summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;

        /// <summary>txtSearch control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        /// <summary>litWishCount control.</summary>
        protected global::System.Web.UI.WebControls.Literal litWishCount;

        /// <summary>litCartCount control.</summary>
        protected global::System.Web.UI.WebControls.Literal litCartCount;

        /// <summary>lnkAuth control.</summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkAuth;

        /// <summary>MainContent control.</summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;

        // ------------------------------------------------------------------ modal login

        /// <summary>pnlLoginCard control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlLoginCard;

        /// <summary>pnlLoginMsg control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlLoginMsg;

        /// <summary>litLoginMsg control.</summary>
        protected global::System.Web.UI.WebControls.Literal litLoginMsg;

        /// <summary>vsModalLogin control.</summary>
        protected global::System.Web.UI.WebControls.ValidationSummary vsModalLogin;

        /// <summary>mtxtEmail control.</summary>
        protected global::System.Web.UI.WebControls.TextBox mtxtEmail;

        /// <summary>mrfvEmail control.</summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator mrfvEmail;

        /// <summary>mrevEmail control.</summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator mrevEmail;

        /// <summary>mtxtPassword control.</summary>
        protected global::System.Web.UI.WebControls.TextBox mtxtPassword;

        /// <summary>mrfvPassword control.</summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator mrfvPassword;

        /// <summary>mcvCredentials control.</summary>
        protected global::System.Web.UI.WebControls.CustomValidator mcvCredentials;

        /// <summary>mchkRemember control.</summary>
        protected global::System.Web.UI.WebControls.CheckBox mchkRemember;

        /// <summary>btnModalLogin control.</summary>
        protected global::System.Web.UI.WebControls.Button btnModalLogin;

        // ------------------------------------------------------------------ modal register

        /// <summary>pnlRegCard control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlRegCard;

        /// <summary>vsModalRegister control.</summary>
        protected global::System.Web.UI.WebControls.ValidationSummary vsModalRegister;

        /// <summary>mrtxtName control.</summary>
        protected global::System.Web.UI.WebControls.TextBox mrtxtName;

        /// <summary>mrfvName control.</summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator mrfvName;

        /// <summary>mrrevName control.</summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator mrrevName;

        /// <summary>mrtxtEmail control.</summary>
        protected global::System.Web.UI.WebControls.TextBox mrtxtEmail;

        /// <summary>mrfvREmail control.</summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator mrfvREmail;

        /// <summary>mrrevEmail control.</summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator mrrevEmail;

        /// <summary>mrcvEmail control.</summary>
        protected global::System.Web.UI.WebControls.CustomValidator mrcvEmail;

        /// <summary>mrtxtPassword control.</summary>
        protected global::System.Web.UI.WebControls.TextBox mrtxtPassword;

        /// <summary>mrfvRPassword control.</summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator mrfvRPassword;

        /// <summary>mrcvPasswordStrength control.</summary>
        protected global::System.Web.UI.WebControls.CustomValidator mrcvPasswordStrength;

        /// <summary>mrtxtConfirm control.</summary>
        protected global::System.Web.UI.WebControls.TextBox mrtxtConfirm;

        /// <summary>mrfvConfirm control.</summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator mrfvConfirm;

        /// <summary>mrcmpPassword control.</summary>
        protected global::System.Web.UI.WebControls.CompareValidator mrcmpPassword;

        /// <summary>mrchkTerms control.</summary>
        protected global::System.Web.UI.WebControls.CheckBox mrchkTerms;

        /// <summary>mrcvTerms control.</summary>
        protected global::System.Web.UI.WebControls.CustomValidator mrcvTerms;

        /// <summary>btnModalRegister control.</summary>
        protected global::System.Web.UI.WebControls.Button btnModalRegister;

        // ------------------------------------------------------------------ modal forgot

        protected global::System.Web.UI.WebControls.Panel pnlForgotCard;
        protected global::System.Web.UI.WebControls.ValidationSummary vsModalForgot;
        protected global::System.Web.UI.WebControls.TextBox mfEmail;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator mrfvFEmail;
        protected global::System.Web.UI.WebControls.CustomValidator mcvFEmail;
        protected global::System.Web.UI.WebControls.Button btnModalForgot;

        // ------------------------------------------------------------------ modal otp

        protected global::System.Web.UI.WebControls.Panel pnlOtpCard;
        protected global::System.Web.UI.WebControls.Literal mlitOtpEmail;
        protected global::System.Web.UI.WebControls.Panel mpnlOtpSent;
        protected global::System.Web.UI.WebControls.Literal mlitOtpMsg;
        protected global::System.Web.UI.WebControls.ValidationSummary vsModalOtp;
        protected global::System.Web.UI.WebControls.TextBox moOtp;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator mrfvOtp;
        protected global::System.Web.UI.WebControls.CustomValidator mcvOtp;
        protected global::System.Web.UI.WebControls.Button btnModalOtp;
        protected global::System.Web.UI.WebControls.LinkButton btnModalOtpResend;

        // ------------------------------------------------------------------ modal reset

        protected global::System.Web.UI.WebControls.Panel pnlResetCard;
        protected global::System.Web.UI.WebControls.ValidationSummary vsModalReset;
        protected global::System.Web.UI.WebControls.TextBox mrstPassword;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator mrfvRstPassword;
        protected global::System.Web.UI.WebControls.CustomValidator mcvRstStrength;
        protected global::System.Web.UI.WebControls.CustomValidator mcvRstNotReused;
        protected global::System.Web.UI.WebControls.TextBox mrstConfirm;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator mrfvRstConfirm;
        protected global::System.Web.UI.WebControls.CompareValidator mcmpRstPassword;
        protected global::System.Web.UI.WebControls.Button btnModalReset;
    }
}
