//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevArt.Admin {


    public partial class AdminMaster {

        /// <summary>form1 control.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>TitleContent control.</summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder TitleContent;

        /// <summary>HeadContent control.</summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;

        /// <summary>litAdminEmail control.</summary>
        protected global::System.Web.UI.WebControls.Literal litAdminEmail;

        /// <summary>btnLogout control.</summary>
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;

        /// <summary>MainContent control.</summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
