//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevArt.Admin {


    public partial class Inventory {

        /// <summary>
        /// TitleContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Content TitleContent;

        /// <summary>
        /// BodyContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Content BodyContent;

        /// <summary>
        /// pnlStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlStatus;

        /// <summary>
        /// litStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litStatus;

        /// <summary>
        /// rptChips control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptChips;

        /// <summary>
        /// rptProducts control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptProducts;

        /// <summary>
        /// pnlEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;

        /// <summary>
        /// btnAddProductFab control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnAddProductFab;

        /// <summary>
        /// pnlProductModal control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlProductModal;

        /// <summary>
        /// lblModalTitle control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblModalTitle;

        /// <summary>
        /// btnCloseModalX control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnCloseModalX;

        /// <summary>
        /// hfProductId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfProductId;

        /// <summary>
        /// hfSelectedImage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfSelectedImage;

        /// <summary>
        /// vsProduct control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ValidationSummary vsProduct;

        /// <summary>
        /// txtName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtName;

        /// <summary>
        /// rfvName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvName;

        /// <summary>
        /// cvName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CustomValidator cvName;

        /// <summary>
        /// ddlCategory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;

        /// <summary>
        /// rfvCategory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCategory;

        /// <summary>
        /// txtPrice control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPrice;

        /// <summary>
        /// rfvPrice control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPrice;

        /// <summary>
        /// rngPrice control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RangeValidator rngPrice;

        /// <summary>
        /// txtStock control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtStock;

        /// <summary>
        /// rfvStock control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvStock;

        /// <summary>
        /// rngStock control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RangeValidator rngStock;

        /// <summary>
        /// txtDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDescription;

        /// <summary>
        /// rfvDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDescription;

        /// <summary>
        /// cvDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CustomValidator cvDescription;

        /// <summary>
        /// chkNew control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkNew;

        /// <summary>
        /// btnCancelModal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancelModal;

        /// <summary>
        /// btnSaveModal control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnSaveModal;

        /// <summary>
        /// btnSaveModalText control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl btnSaveModalText;

        /// <summary>
        /// btnDeleteModal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnDeleteModal;

        /// <summary>
        /// pnlSuccessModal control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlSuccessModal;

        /// <summary>
        /// lblSuccessTitle control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblSuccessTitle;

        /// <summary>
        /// lblSuccessSub control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblSuccessSub;

        /// <summary>
        /// btnBackToInventory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnBackToInventory;

        /// <summary>
        /// pnlConfirmDeleteModal control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlConfirmDeleteModal;

        /// <summary>
        /// hfDeleteProductId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfDeleteProductId;

        /// <summary>
        /// btnConfirmDelete control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConfirmDelete;

        /// <summary>
        /// btnCancelDelete control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancelDelete;

        /// <summary>
        /// pnlSuccessDeleteModal control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlSuccessDeleteModal;

        /// <summary>
        /// btnReturnToInventory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnReturnToInventory;
    }
}


