//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevArt.Admin {


    public partial class AdminOffers {

        /// <summary>
        /// TitleContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Content TitleContent;

        /// <summary>
        /// BodyContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Content BodyContent;

        /// <summary>
        /// pnlStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlStatus;

        /// <summary>
        /// litStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litStatus;

        /// <summary>
        /// rptOffers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptOffers;

        /// <summary>
        /// pnlEmpty control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;

        /// <summary>
        /// pnlOfferModal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlOfferModal;

        /// <summary>
        /// lblModalTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblModalTitle;

        /// <summary>
        /// btnCloseModal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnCloseModal;

        /// <summary>
        /// hfOfferId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfOfferId;

        /// <summary>
        /// pnlModalError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlModalError;

        /// <summary>
        /// litModalError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litModalError;

        /// <summary>
        /// txtKicker control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtKicker;

        /// <summary>
        /// txtTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTitle;

        /// <summary>
        /// txtCode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCode;

        /// <summary>
        /// ddlType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlType;

        /// <summary>
        /// pnlValue control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlValue;

        /// <summary>
        /// lblValueLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblValueLabel;

        /// <summary>
        /// txtDiscountValue control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDiscountValue;

        /// <summary>
        /// txtMinSpend control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtMinSpend;

        /// <summary>
        /// txtExpiry control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtExpiry;

        /// <summary>
        /// chkActive control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkActive;

        /// <summary>
        /// chkOneTime control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkOneTime;

        /// <summary>
        /// btnCancelModal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancelModal;

        /// <summary>
        /// btnSaveOfferModal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSaveOfferModal;

        /// <summary>
        /// btnDeleteOfferModal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnDeleteOfferModal;

        /// <summary>
        /// pnlSuccessModal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSuccessModal;

        /// <summary>
        /// lblSuccessTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSuccessTitle;

        /// <summary>
        /// lblSuccessSub control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSuccessSub;

        /// <summary>
        /// btnBackToOffers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnBackToOffers;

        /// <summary>
        /// pnlConfirmDeleteOfferModal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlConfirmDeleteOfferModal;

        /// <summary>
        /// hfDeleteOfferId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfDeleteOfferId;

        /// <summary>
        /// btnConfirmDeleteOffer control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConfirmDeleteOffer;

        /// <summary>
        /// btnCancelDeleteOffer control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancelDeleteOffer;

        /// <summary>
        /// pnlSuccessDeleteOfferModal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSuccessDeleteOfferModal;

        /// <summary>
        /// btnReturnToOffersAfterDelete control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnReturnToOffersAfterDelete;
    }
}
